### ISSUE TITLE
Config block style

### ISSUE THREAD

**Issue by dmytroyarmak** [nilaneo/marvel-characters#10]
In `marvel-characters-app.js` you have config block that doesn't match Style Guide:

https://github.com/nilaneo/marvel-characters/blob/master/app/marvel-characters-app.js#L15-L17
https://github.com/johnpapa/angular-styleguide#configuration-1

**Comment by nilaneo** [comment]
Done https://github.com/nilaneo/marvel-characters/commit/a4fec2d20f8f1383c9c27307397533d64b1436b6
