### ISSUE TITLE
Naming of object returned from marvelApi service factory 

### ISSUE THREAD

**Issue by dmytroyarmak** [nilaneo/marvel-characters#11]
According to Style Guide name of object returned from factory should be `service`:
https://github.com/johnpapa/angular-styleguide#factories
https://github.com/nilaneo/marvel-characters/blob/master/app/common/services/marvel-api.js#L9-L17

**Comment by nilaneo** [comment]
Done https://github.com/nilaneo/marvel-characters/commit/a4fec2d20f8f1383c9c27307397533d64b1436b6
