### ISSUE TITLE
Constants naming convention

### ISSUE THREAD

**Issue by dmytroyarmak** [nilaneo/marvel-characters#12]
According to many JS code style guides, variable names with constant should be in upper case with `_` between words like `API_KEY` or `SOME_VALUE`:
https://github.com/nilaneo/marvel-characters/blob/master/app/common/services/marvel-api.js#L14-L15
https://github.com/nilaneo/marvel-characters/blob/master/app/pages/marvel-characters-list/marvel-characters-list.js#L91-L92

**Comment by nilaneo** [comment]
Done https://github.com/nilaneo/marvel-characters/commit/95bd42b1efd7aaa3d08b6cff08b2c94a212c843f
