### ISSUE TITLE
thumbnailUrl method name

### ISSUE THREAD

**Issue by dmytroyarmak** [nilaneo/marvel-characters#13]
In `MarvelCharacterImgCtrl` you have `thumbnailUrl` and this method returns `thumbnailUrl`. This method is actually a "getter" and according to most of the JS style guides it's better to name it like `getThumbnailUrl`:
https://github.com/nilaneo/marvel-characters/blob/master/app/common/directives/marvel-character-img/marvel-character-img.js#L25-L31

**Comment by nilaneo** [comment]
Done https://github.com/nilaneo/marvel-characters/commit/6c5e91ff10ad71fccdabe6830f6e03e51332d3ac
