### ISSUE TITLE
Move MarvelCharacterImgCtrl to function declaration

### ISSUE THREAD

**Issue by dmytroyarmak** [nilaneo/marvel-characters#14]
This constoller (MarvelCharacterImgCtrl) is initialized as an anonymous function, but according to Style Guide it should be function declaration.

https://github.com/nilaneo/marvel-characters/blob/master/app/common/directives/marvel-character-img/marvel-character-img.js#L25-L31

**Comment by nilaneo** [comment]
Done https://github.com/nilaneo/marvel-characters/commit/23e6481922d37964b4b9076137ebbbbf2b712243
