### ISSUE TITLE
Unused thumbnailUrl method in marvelCharacterInfo

### ISSUE THREAD

**Issue by dmytroyarmak** [nilaneo/marvel-characters#15]
Because you are using marver thumbnail directive, you don't need this method anymore:
https://github.com/nilaneo/marvel-characters/blob/master/app/common/directives/marvel-character-info/marvel-character-info.js#L26-L30

**Comment by nilaneo** [comment]
Done https://github.com/nilaneo/marvel-characters/commit/6c5e91ff10ad71fccdabe6830f6e03e51332d3ac
