### ISSUE TITLE
MarvelCharacterDetailsCtrl improvements

### ISSUE THREAD

**Issue by dmytroyarmak** [nilaneo/marvel-characters#17]
1. You don't need to have `getCharacter` method attached to the controller's `vm` because you don't need to call it from template
2. It's better to use `activate` method name for initializing logic of controller to be consistent with another page +  Style Guide

https://github.com/nilaneo/marvel-characters/blob/master/app/pages/marvel-character-details/marvel-character-details.js

**Comment by nilaneo** [comment]
Done https://github.com/nilaneo/marvel-characters/commit/23e6481922d37964b4b9076137ebbbbf2b712243
