### ISSUE TITLE
Move characters list params initialization to separate functions

### ISSUE THREAD

**Issue by dmytroyarmak** [nilaneo/marvel-characters#18]
Now you have complex logic of validation and setting default `currentPage`, `itemsPerPage` and `orderBy` inside controller main function. It's better to move this logic to separate functions and call them from main function like:

```
vm.itemsPerPage = getInitialItemsPerPage();
vm.currentPage = gegtInitialCurrentPage();
vm.orderBy = getInitialOrderBy();
```

https://github.com/nilaneo/marvel-characters/blob/master/app/pages/marvel-characters-list/marvel-characters-list.js#L26-L28
https://github.com/nilaneo/marvel-characters/blob/master/app/pages/marvel-characters-list/marvel-characters-list.js#L37-L50

**Comment by nilaneo** [comment]
Done https://github.com/nilaneo/marvel-characters/commit/23e6481922d37964b4b9076137ebbbbf2b712243
