### ISSUE TITLE
No items are loading when navigating to page with invalid page number and valid items and vice verca

### ISSUE THREAD

**Issue by dmytroyarmak** [nilaneo/marvel-characters#4]
1. Open page with params: [http://localhost:3000/#/?items=INVALID&page=1](http://localhost:3000/#/?items=INVALID&page=1) 
   or 
   [http://localhost:3000/#/?items=20&page=INVALID](http://localhost:3000/#/?items=20&page=INVALID)

AR:
Nothing is loading
ER:
Page should be changed to 1

**Comment by nilaneo** [comment]
Fixed - https://github.com/nilaneo/marvel-characters/commit/57cad425aac277500ded2c30f7ce3607bff012ad
