### ISSUE TITLE
Empty "items per page" input when load page with not-supported items value 

### ISSUE THREAD

**Issue by dmytroyarmak** [nilaneo/marvel-characters#6]
[http://localhost:3000/#/?items=15&page=1](http://localhost:3000/#/?items=15&page=1)

AR:
List loaded with 15 items but select for "items per page" is empty

ER:
If value is invalid we should fallback to default value

**Comment by nilaneo** [comment]
Fixed - https://github.com/nilaneo/marvel-characters/commit/57cad425aac277500ded2c30f7ce3607bff012ad
