### ISSUE TITLE
No error message in case of server error

### ISSUE THREAD

**Issue by dmytroyarmak** [nilaneo/marvel-characters#7]
There is a problem with Marvel API that for request on last page when you have 100 items per page always failed with 500 error. It's also possible that API can return errors in other cases.

[http://localhost:3000/#/?items=100&page=15](http://localhost:3000/#/?items=100&page=15)

AR:
Nothing happened if API returns error

ER:
User should see some error message if something was wrong when requesting data from the API.

**Comment by nilaneo** [comment]
Done https://github.com/nilaneo/marvel-characters/commit/612cf9a91982ee3667bf44f50085cdecc213e620
