### ISSUE TITLE
Move inline styles from index.html to CSS files

### ISSUE THREAD

**Issue by dmytroyarmak** [nilaneo/marvel-characters#9]
You have some styles in `style` tag in `index.html`:
https://github.com/nilaneo/marvel-characters/blob/master/index.html#L12-L16

It's better to have all styles in one place :)

**Comment by nilaneo** [comment]
Done https://github.com/nilaneo/marvel-characters/commit/14175d99656caf681542b3b2c1857e939349e8d7
